"""Shared test fixtures and data."""

import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

import pytest
from data.loader import Place


@pytest.fixture
def sample_places() -> list[Place]:
    """Return a set of sample places for testing."""
    return [
        Place(
            name="Thai Basil",
            type="restaurant",
            cuisine_tags=["thai", "noodles"],
            style_tags=["casual"],
            address="123 Wan Chai Rd, Wan Chai",
            lat=22.2790,
            lng=114.1750,
            google_rating=4.5,
            review_count=150,
            opening_hours="Mo-Su 11:00-22:00",
            booking_url="https://chope.com/thaibasil",
            booking_platform="chope",
            is_secret_gem=True,
        ),
        Place(
            name="Italian Bistro",
            type="restaurant",
            cuisine_tags=["italian"],
            style_tags=["fine-dining"],
            address="45 Central Rd, Central",
            lat=22.2783,
            lng=114.1540,
            google_rating=4.2,
            review_count=300,
            opening_hours="Mo-Su 12:00-23:00",
            booking_url="",
            is_secret_gem=False,
        ),
        Place(
            name="Cocktail Palace",
            type="bar",
            cuisine_tags=["cocktail-bar", "speakeasy"],
            style_tags=["date-night"],
            address="78 Soho, Central",
            lat=22.2800,
            lng=114.1530,
            google_rating=4.6,
            review_count=80,
            opening_hours="Mo-Su 17:00-02:00",
            is_secret_gem=True,
        ),
        Place(
            name="Sushi Master",
            type="restaurant",
            cuisine_tags=["japanese", "sushi"],
            style_tags=["fine-dining"],
            address="10 Causeway Bay Rd",
            lat=22.2810,
            lng=114.1850,
            google_rating=4.8,
            review_count=500,
            opening_hours="Mo-Su 11:30-22:00",
            is_secret_gem=False,
        ),
        Place(
            name="Ramen House",
            type="restaurant",
            cuisine_tags=["japanese", "ramen", "noodles"],
            style_tags=["casual", "late-night"],
            address="55 Mong Kok Rd",
            lat=22.3190,
            lng=114.1690,
            google_rating=4.1,
            review_count=250,
            opening_hours="Mo-Su 11:00-02:00",
            is_secret_gem=False,
        ),
        Place(
            name="Vietnamese Pho",
            type="restaurant",
            cuisine_tags=["vietnamese", "noodles"],
            style_tags=["casual"],
            address="22 TST Rd",
            lat=22.2970,
            lng=114.1700,
            google_rating=4.0,
            review_count=50,
            opening_hours="Mo-Su 10:00-21:00",
            is_secret_gem=False,
        ),
        Place(
            name="Wine Vault",
            type="bar",
            cuisine_tags=["wine-bar"],
            style_tags=["date-night", "chill"],
            address="33 Sheung Wan Rd",
            lat=22.2860,
            lng=114.1500,
            google_rating=4.3,
            review_count=90,
            opening_hours="Mo-Su 16:00-00:00",
            is_secret_gem=True,
        ),
        Place(
            name="Craft Beer Lab",
            type="bar",
            cuisine_tags=["craft-beer", "pub"],
            style_tags=["casual", "group"],
            address="88 Sai Ying Pun Rd",
            lat=22.2860,
            lng=114.1420,
            google_rating=4.0,
            review_count=200,
            opening_hours="Mo-Su 15:00-01:00",
            is_secret_gem=False,
        ),
        Place(
            name="Spanish Tapas",
            type="restaurant",
            cuisine_tags=["spanish"],
            style_tags=["casual", "group"],
            address="12 Star St, Wan Chai",
            lat=22.2790,
            lng=114.1730,
            google_rating=4.4,
            review_count=120,
            opening_hours="Mo-Su 12:00-23:00",
            is_secret_gem=True,
        ),
        Place(
            name="Dim Sum Palace",
            type="restaurant",
            cuisine_tags=["cantonese", "dim-sum", "chinese"],
            style_tags=["casual"],
            address="100 North Point Rd",
            lat=22.2910,
            lng=114.1970,
            google_rating=4.2,
            review_count=800,
            opening_hours="Mo-Su 07:00-15:00",
            is_secret_gem=False,
        ),
    ]
